### ISSUE TITLE
no_wrap option

### ISSUE THREAD

**Issue by rambip** [blocklessnetwork/blockless-car#59]
Hi !

I would like to use your library in my own project, but I have an issue.
I would like to generate a car-file (to use it with a HTTP api afterwards) but by default it wraps the file in a directory, and I don't want that.
If the IPFS docs (see [here](bafybeiaa5pm2v3slhn7gjtzznvu5ocmnqosd7wdxtm2etvsitlzxlpb6t4)), they give an option to skip this wrapping:

```bash
ipfs-car pack path/to/file --no-wrap --output path/to/write/a.car
```

It would be nice to add this option to your library !

**Comment by dmikey** [comment]
Thanks for the feedback!

**Comment by zees-dev** [comment]
The `blockless-car` lib has been migrated to https://github.com/blocklessnetwork/car-utils (utilizing cargo workspace).
This issue will be addressed there.
